### ISSUE TITLE
Animate number

### ISSUE THREAD

**Issue by ronakmob** [alexzaitsev/meter-number-picker#1]
Hi,

This is wonderful library I came across, I have a question regarding number scroll animation. Is there any way I can add `mv.setValue(250)` and it should quickly scroll animate number to 250.

I appreciate.
Thanks

**Comment by alexzaitsev** [comment]
Hi, @ronakmob 
Unfortunately, it isn't possible for now. If you'd like to implement it - your contribution will be highly appreciated!
